// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace WhoseTurn.Common.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddGroupId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGroupId));
        
        string IMigrationMetadata.Id
        {
            get { return "201610090421334_AddGroupId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
